---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
now I wonder what you're at!'You know the song, perhaps?" "I've heard something like it," said Alice.  
 "It goes on, you know," the Hatter continued,  
"in this way: -- --   
`Up above the world you fly,  
Like a teatray in the sky.  

"You are old, Father William," the young man said,  
"And your hair has become very white;  
And yet you incessantly stand on your head—  
Do you think, at your age, it is right?"  
"In my youth," Father William replied to his son,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

He gives his harness bells a shake   
To ask if there is some mistake.     
The only other sound’s the sweep   
Of easy wind and downy flake.   

The woods are lovely, dark and deep,   
But I have promises to keep,   
And miles to go before I sleep,   
And miles to go before I sleep.
Pink and perfect mystery   
to which I ply my finger,   
she ripens so exquisitely  
the longer that I linger  

and fluff the modest blossom  
with my gentle loving hand,  
teasing, ever pleasing  
so that now I understand  
